language: node_js
node_js:
  - '13'

branches:
only:
  - master

before_script:
  - npm install -g firebase-tools

cache:
  directories:
    - 'node_modules'

script:
  - yarn build
  - yarn test

  after_success: 
    - firebase deploy --token $FIREBASE_TOKEN

notifications:
email:
recipients:
  - naimlatifi98@hotmail.com
on_success: always
on_failure: always
