language: node_js
node_js:
  - '13'

branches:
only:
  - master

cache:
  directories:
    - 'node_modules'

script:
  - yarn build
  - yarn test

notifications:
email:
recipients:
  - naimlatifi98@hotmail.com
on_success: always
on_failure: always
